ASU-1002: Add HASO lottery logic
City-of-Helsinki/apartment-application-service pull request #103
Opened 2021-08-25 12:41 UTC by jmp

This PR adds HASO lottery logic to the backend.

Strictly speaking the HASO apartment distribution doesn't have "lottery", but I chose to call it lottery anyway to keep things consistent with the HITAS flow.

When an application is created, it is automatically added to a reservation queue for each apartment applied to in the application. This reservation queue works for both HITAS and HASO apartments, but in HASO case the applications in each queue are kept in an order based on their right of residence number. The lower the number, the higher precedence the application has.

When the application period has finished, we can call the `reserve_haso_apartment` function to declare the winner for a given apartment. Before declaring a winner, the current queue is persisted to database. The winning application for that apartment will be marked as `RESERVED`. If the same application applied to other apartments with a lower priority, those applications will be removed from their queues and marked as `REJECTED`. If there are multiple winning applications (with the same right of residence number) the applications with duplicate numbers are still treated as winners but marked as `REVIEW` so that they can be looked into in more detail.

Applications can be added to or removed from the queue manually with a comment. In such case (for example, removing an application who declined an apartment), a change event is recorded into the database.

2021-08-25 16:04 UTC, tomijarvi commented
This needs a bit of time to review so I'll let you know when I have done a full review.

2021-08-25 16:15 UTC, tomijarvi commented on application_form/models.py
> +class ReservationQueue(models.Model):
The name of this model could be better if it is `HousingQueue` (Asuntojono). The reservation state is one of the states in the item.

2021-08-30 09:35 UTC, jmp commented
Clarified a couple of things with the PO:

* When an application is marked as RESERVED and then cancelled afterwards, the next applicant in line should be marked as RESERVED.
* When a late application is added to the queue, it is added last. However multiple late applications form their own "pool" and should be kept in order based on their right of residence number.

2021-09-01 09:43 UTC, jmp commented
Made the (hopefully) final changes related to persisting the initial queue positions:

* Apartments are distributed at the same time for the whole project, not one apartment at a time.
* Before marking any applications as "RESERVED", "CANCELED", etc., the queue is persisted to database.
* Only after that the apartments are distributed to the applicants.

For this reason I changed the internal API a bit: instead of reserving apartments with `reserve_haso_apartment(apartment)`, you call the `distribute_haso_apartments(project)` function, which internally processes all the apartments belonging to that project.

2021-09-07 05:37 UTC, frwickst requested changes
Overall this shaping up nicely now. I have to say that reading the code is a joy as it is very well structured and easy to read, really good work @jmp !

Some minor notes that might be worth looking at still, nothing major.

2021-09-07 05:42 UTC, jmp commented on application_form/services/queue.py
> +                position = queue.queue_applications.count()
This is a great suggestion. From the apartment lottery point of view, Hitas and Puolihitas are exactly the same, but this is not obvious at the moment.

2021-09-07 06:18 UTC, jmp commented on application_form/services/queue.py
> +    of the application for this apartment will be updated to "REJECTED".
Good catch, fixed in the latest changeset.

2021-09-07 06:28 UTC, frwickst approved these changes
LGTM 👍

2021-09-07 06:30 UTC, merged